export {default as Home} from "./Home"
export {default as Cart} from "./Cart"
export {default as Favorite} from "./Favorite"
export { default as Details } from "./Details"
export { default as Login } from "./Login"
export { default as Profile } from "./Profile"
export { default as Setting } from "./Setting"